fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-docstring-first
      - id: detect-private-key
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        additional_dependencies: [
          mypy-extensions==1.0.0,
          types-requests==2.31.0.1,
        ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.275
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["themoviedb"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["themoviedb"]

  - repo: local
    hooks:
      - id: test
        name: test
        stages: [manual, commit, push]
        language: system
        entry: make test
        types: [python]
        pass_filenames: false
        always_run: true
