name: Debug Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Bước 1: Check out mã nguồn
      - name: Check out 
        uses: actions/checkout@v4
        with:
          submodules: true

      # Bước 2: Cài đặt Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle

      # Bước 3: Thiết lập Android SDK
      - name: Set up android
        uses: android-actions/setup-android@v3
        with:
          api-level: cmdline-tools-version
          build-tools: accept-android-sdk-licenses

      # Bước 4: Cấp quyền thực thi cho gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Bước 5: Cài đặt các dependencies
      - name: Install Dependencies
        run: ./gradlew dependencies
        
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Run UI Tests
        run: ./gradlew connectedAndroidTest
        
      # Bước 6: Build ứng dụng Debug
      - name: Build Debug App
        run: ./gradlew assembleDebug

      # Bước 7: Upload file APK Debug
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: RottenEgg.apk
          path: app/build/outputs/apk/debug/app-debug.apk
