name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-lates

    strategy:
      matrix:
        api-level: [30]          # Đặt API level cho các test
        target: [google_apis]     # Sử dụng google_apis để hỗ trợ máy ảo với API của Google
        abi: [x86_64]             # Kiến trúc của máy ảo

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Download dependencies
      run: ./gradlew build --no-daemon

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: ${{ matrix.abi }}

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Start emulator
      run: |
        sudo apt-get update
        sudo apt-get install qemu-kvm -y
        echo "hw.cpu.ncore=2" >> ~/.android/avd/Pixel_API_30_AOSP.ini
        $ANDROID_HOME/emulator/emulator -avd Pixel_API_30_AOSP -no-snapshot-load -no-window -gpu swiftshader_indirect &
        adb wait-for-device
        adb shell input keyevent 82 &
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}

    - name: Wait for emulator to boot
      run: |
        adb wait-for-device
        adb shell settings put global window_animation_scale 0 &
        adb shell settings put global transition_animation_scale 0 &
        adb shell settings put global animator_duration_scale 0 &
      timeout-minutes: 5

    - name: Run instrumented tests
      run: ./gradlew connectedAndroidTest --no-daemon
      env:
        ADB_INSTALL_TIMEOUT: 10
