name: Debug Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out 
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle

      - name: Set up android
        uses: android-actions/stetup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
      - name: Install Dependencies
        run: ./gradlew dependencies

      - name: Build Debug App
        run: ./gradlew assembleDebug

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: RostenEgg.apk
          path: app/build/outputs/apk/debug/app-debug.apk
